# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-54fc0a41-1197-4920-a9b3-e5d3087591b1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-54fc0a41-1197-4920-a9b3-e5d3087591b1".device = "/dev/disk/by-uuid/54fc0a41-1197-4920-a9b3-e5d3087591b1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/07DF-0005";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-75ea70ff-55c3-40ce-b1d1-99a375e4c671"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
