# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3c6276ca-f4a4-4007-aaa2-a6751a3f1641";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3c6276ca-f4a4-4007-aaa2-a6751a3f1641".device = "/dev/disk/by-uuid/3c6276ca-f4a4-4007-aaa2-a6751a3f1641";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A95C-ACCE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-30341dbb-392c-4f7f-a167-4e8f808eb0f4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
