# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1adc151d-82ff-4d10-9fb6-7b1176dbce8a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1adc151d-82ff-4d10-9fb6-7b1176dbce8a".device = "/dev/disk/by-uuid/1adc151d-82ff-4d10-9fb6-7b1176dbce8a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/248B-DA3B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b93ba4c5-0189-426b-84fe-3a13ae6e0ef3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
